app/comment/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, HiddenField
from wtforms.validators import Length
from flask_ckeditor import CKEditorField


class LeaveCommentForm(FlaskForm):
    comment_content = CKEditorField('Leave your comment', validators=[Length(min=1, max=200)])
    pu_id = HiddenField('Hidden field')
    submit = SubmitField('Send')


class EditCommentForm(FlaskForm):
    hidden_com_id = HiddenField('edit-comment')
    submit = SubmitField('Update')


class DeleteCommentForm(FlaskForm):
    hidden_com_id = HiddenField('delete-comment')
    submit = SubmitField('Delete')

app/comment/__init__.py
from flask import Blueprint

comment = Blueprint('comment', __name__, template_folder='templates')

from . import views

app/comment/views.py
from . import comment
from flask import flash, redirect, url_for, jsonify
from flask_login import login_required, current_user
from .forms import LeaveCommentForm, EditCommentForm, DeleteCommentForm
from app.models import Articles, Comments
from app import db


@comment.route('/leave_comment/<int:post_id>', methods=['POST'])
@login_required
def leave_comment(post_id=0):
    mform = LeaveCommentForm()
    comment_content = mform.comment_content.data
    if not comment_content:
        flash('Comment can not be empty!', 'error')
    else:
        if len(comment_content) > 200:
            flash('Max comment length is 200 symbols!', 'error')
        else:
            article = db.session.query(Articles).filter_by(id=post_id).first()
            if article:
                new_comment = Comments(comment_text=comment_content, author=current_user.id, post_id=post_id)
                db.session.add(new_comment)
                db.session.commit()
                flash('Comment was added!', 'success')
            else:
                flash('Article does not exists!', 'error')
    return redirect(url_for('blog.show_article', article_id=post_id))


@comment.route('/edit_comment/<int:post_id>/', methods=['POST'])
@login_required
def edit_comment(post_id=0):
    edit_comment_form = EditCommentForm()
    response = 'success'
    if edit_comment_form.validate_on_submit():
        comment_id = edit_comment_form.hidden_com_id.data
        comment_id, body = comment_id.split('|', 1)
        comment_id = comment_id.strip()

        if comment_id:
            if db.session.query(Comments).filter_by(id=comment_id).first():
                db.session.query(Comments).filter_by(id=comment_id).update({'comment_text': body})
                db.session.commit()
            else:
                response = 'There is no comment which you want to edit!'
        else:
            response = 'Unknown error!'
    return jsonify({'msg': response})


@comment.route('/delete_comment', methods=['POST'])
@login_required
def delete_comment():
    msg = dict()
    del_form = DeleteCommentForm()
    comment_id = del_form.hidden_com_id.data
    if del_form.validate_on_submit():
        current_comment = db.session.query(Comments).filter_by(id=comment_id).first()
        if current_user.id == current_comment.author or current_user.info.admin:
            db.session.delete(current_comment)
            db.session.commit()
            msg = {'msg': 'Comment was deleted successfully!', 'status': 'success'}
        else:
            msg = {'msg': 'Error', 'status': 'error'}
            flash('You have no permissions to delete this comment!', 'error')
    else:
        msg = {'msg': 'error', 'status': 'error'}
    return jsonify(msg)

app/comment/templates/comment/comment_form.html
<form method="post" action="{{ url_for('comment.leave_comment',post_id=article.id) }}">
    {{ leave_comment_form.csrf_token(id='comment-csrf') }}
    <div class="mb-3">
            {{ leave_comment_form.comment_content.label() }}
             <br><br>
            {{ leave_comment_form.comment_content(id='comment-field') }}
        </div>
            {{ leave_comment_form.pu_id() }}

     {{ leave_comment_form.submit(class='btn btn-success') }}
</form>

app/comment/templates/comment/comments.html
<div id="comment-status"></div>
<div class="shadow p-3 mb-5 bg-white rounded ">

    <div class="d-flex flex-column">
        <div class="p-2 text-center"><a class="btn btn-dark " href="#cke_comment-field">Leave comments</a></div>
        <div class="p-2">
        <div>Comments</div>
        <div style="padding:0;"><hr></div>
        <div id="comment-card">
            {% for comment in comments %}
                <div class="shadow-none p-3 mb-1 bg-light rounded" id="cm-block-{{ comment.id }}">
                    <div class="d-flex justify-content-between">
                        <div>
                            <div>By: <b>{{ comment.user.name }}</b><small class="comment-date">&nbsp;&nbsp;&nbsp;&nbsp;{{ comment.on_update | article_date_format() }}</small></div>
                        </div>
                        {% if current_user.is_authenticated %}
                            {% if current_user.name == comment.user.name or current_user.info.admin %}
                                <div class="d-flex">
                                    <a type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#comment-id_{{ comment.id }}">Edit</a>
                                    {% include 'comment/delete_comment_form.html' %}
                                </div>
                            {% endif %}
                        {% endif %}
                    </div>
                    <br>
                    <div class="comment-text">{{ comment.comment_text | safe }}</div>
                </div>
                {% include 'comment/edit_comment_modal.html' %}
            {% endfor %}
        </div>
        </div>
    </div>
</div>
<div class="shadow p-3 mb-5 bg-white rounded">
    {% if current_user.is_authenticated %}
        {% include 'comment/comment_form.html' %}
        {{ ckeditor.load() }}
        {{ ckeditor.config(name='comment_content', height=100) }}
    {% else %}
        <div class="text-center">You must be logged in to post a comment. <a href="{{ url_for('auth.login') }}">Login</a></div>
    {% endif %}
</div>

app/comment/templates/comment/delete_comment_form.html
<form method="post" action="{{ url_for('comment.delete_comment') }}" class="delete-comment-form" id="delete-comment-form-{{ comment.id }}">
    {{ delete_comment_form.csrf_token() }}
    {{ delete_comment_form.hidden_com_id(value=comment.id) }}
    {{ delete_comment_form.submit(class='btn btn-danger', id='btn-delete-'+ (comment.id | string)) }}
</form>

app/comment/templates/comment/edit_comment_modal.html
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
</svg>


<div class="modal fade" id="comment-id_{{ comment.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Update comment</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body modal-body-border">
           <div id="ajax-message-{{ comment.id }}"></div>
          <form method="post" action="{{ url_for('comment.edit_comment', post_id=article.id) }}"
                id="edit-comment-{{ comment.id }}" onsubmit="return false;">

                  {{ edit_comment_form.csrf_token() }}
                  {{ ckeditor.create(value=comment.comment_text) }}
                  {{ edit_comment_form.hidden_com_id(value=comment.id) }}
              <br>
              <div class="d-flex justify-content-end">
                <div class=""><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button></div>
                <div style="margin-left:5px;">{{ edit_comment_form.submit(class='btn btn-primary', id='cm-id-'+ (comment.id | string)) }}</div>
              </div>
          </form>
      </div>
    </div>
  </div>
</div>